# These symbols will only show when battery levels are 20% or less
[battery]
    full_symbol = " "
    charging_symbol = " "
    discharging_symbol = " "
    format = "[$symbol$percentage]($style) "

# "bold red" style when capacity is between 0% and 10%
[[battery.display]]
    threshold = 10
    style = "bold red"

# "bold orange" style when capacity is between 10% and 25%
[[battery.display]]
    threshold = 25
    style = "bold orange"

# "bold yellow" style when capacity is between 25% and 50%
[[battery.display]]
    threshold = 50
    style ="bold yellow"

# "bold green" style when capacity is between 25% and 50%
[[battery.display]]
    threshold = 100
    style ="bold green"

[character]
    error_symbol = "[✗](bold red) "

[python]
    symbol = " "
    pyenv_version_name = true
    pyenv_prefix = ""
    style = "bold green"

# Clear visibility for exit codes
[status]
    symbol = "💣 "
    format = '[\[$symbol$status\]]($style) '
    disabled = false

[time]
    disabled = false
    format = '[\[🕙 $time\]]($style) '
